### ISSUE TITLE
UI Design (Register page)

### ISSUE THREAD

**Issue by math-alpha** [DSC-UB/travel_mobile#3]
Create a design for the register_activity of the mobile travel app project on figma. To complete this task, you can request for edit access to the public figma file here or a link to your design.

**Comment by allenbangai** [comment]
Hi @math-alpha , I solve this isseu right right...

**Comment by math-alpha** [comment]
Your pull request was merged right @allenbangai ?

**Comment by allenbangai** [comment]
Yes it was thanks...
