### ISSUE TITLE
UI Design (navigation drawer profile)

### ISSUE THREAD

**Issue by allenbangai** [DSC-UB/travel_mobile#5]
Create a circular imageView for profile image and TextView for username on the Navigation profile as shown on the image below.
Clone and run the app to have a proper view of what am saying
![photo_2019-10-10_15-50-57](https://user-images.githubusercontent.com/46921711/66580227-f673dc80-eb75-11e9-9abf-58a0c58501e2.jpg)

**Comment by SimonSickle** [comment]
I am going to start working on this
